### ISSUE TITLE
Decorator doesn't demonstrate overriding behaviour, only extending it

### ISSUE THREAD

**Issue by westonal** [dbacinski/Design-Patterns-In-Kotlin#12]
As it is, the example compiles and has the same effect as if it didn't have `: CoffeeMachine by coffeeMachine` so it is really only demonstrating composition.

```
//Decorator:
class EnhancedCoffeeMachine(val coffeeMachine: CoffeeMachine) : CoffeeMachine by coffeeMachine {

    //overriding behaviour
    override fun makeLargeCoffee() = println("Enhanced: Making large coffee")

    //extending behaviour 

    fun makeCoffeeWithMilk() {
        println("Enhanced: Making coffee with milk")
        coffeeMachine.makeSmallCoffee()
        println("Enhanced: Adding milk")
    }

    fun makeDoubleLargeCoffee() {
        println("Enhanced: Making double large coffee")
        coffeeMachine.makeLargeCoffee()
        coffeeMachine.makeLargeCoffee()
    }
}
```

Usage:
```
    val normalMachine = NormalCoffeeMachine()
    val enhancedMachine = EnhancedCoffeeMachine(normalMachine)

    // non-overridden behaviour
    enhancedMachine.makeSmallCoffee()
    
    // overridden behaviour
    enhancedMachine.makeLargeCoffee()
    
    //extended behaviour (not sure why there's need for two examples of this)
    enhancedMachine.makeCoffeeWithMilk()

    enhancedMachine.makeDoubleLargeCoffee()
```

**Comment by dbacinski** [comment]
Thanks for valuable feedback.

My only concern is that overriding methods (without changing interface) is role of Proxy pattern. People might get confused what is a difference between those two patterns.

Would you like to create PR with this updated example?

**Comment by westonal** [comment]
Sure

**Comment by westonal** [comment]
Decorator/Adapters are proxy patterns. Just look at the wiki example of decorator: https://en.wikipedia.org/wiki/Decorator_pattern

**Comment by westonal** [comment]
I guess the overriding behaviour should demonstrate how it can add to an existing call and still call the decorated, rather than completely replace:

```
//overriding behaviour
override fun makeLargeCoffee() {
    coffeeMachine.makeLargeCoffee()
    println("Enhanced: makeLargeCoffee")
}
```

more like that, but will put in PR for comment.

**Comment by dbacinski** [comment]
+1

**Comment by dbacinski** [comment]
@westonal how is going? I will make those changes if you do not have time to prepare PR.

**Comment by westonal** [comment]
Up to you, I can do on weekend or you can do it. Also happy to review your PR if you @ me.

**Comment by dbacinski** [comment]
@westonal https://github.com/dbacinski/Design-Patterns-In-Kotlin/pull/13
