### ISSUE TITLE
Improvement For The Factory Example

### ISSUE THREAD

**Issue by Amirko28** [dbacinski/Design-Patterns-In-Kotlin#19]
The following code utilizes the sealed class keyword in Kotlin. I think it can be an improvement for the example in the Factory section. Will be glad to hear your opinion:

interface Currency {
    val code: String
}

class Euro(override val code: String = "EUR") : Currency
class UnitedStatesDollar(override val code: String = "USD") : Currency
class UnitedKingdomPound(override val code: String = "GBP") : Currency

sealed class Country 

data class UnitedStates(val name: String = "US"): Country()
data class Spain(val name: String = "Spain"): Country()
data class UK(val name: String = "UK"): Country()
data class Greece(val name: String = "Greece"): Country()

class CurrencyFactory {
    fun currencyForCountry(country: Country): Currency {
        return when (country) {
            is Spain, is Greece -> Euro()
            is UnitedStates     -> UnitedStatesDollar()
            is UK -> UnitedKingdomPound()
        }
    }
}

**Comment by dbacinski** [comment]
Yep, it is a good alternative to use sealed class instead of enum, especially when Country is something more then a dummy value.  

For such simple example enum syntax is much more concise.

**Comment by dbacinski** [comment]
Refactored to make use of sealed classes: https://github.com/dbacinski/Design-Patterns-In-Kotlin/blob/master/patterns/src/test/kotlin/FactoryMethod.kt
