### ISSUE TITLE
fields after methods

### ISSUE THREAD

**Issue by lalilulelo1986** [dbacinski/Design-Patterns-In-Kotlin#25]
[https://github.com/dbacinski/Design-Patterns-In-Kotlin#state](url)

val isAuthorized: Boolean
val userLogin: String
mb better put them after state field?

**Comment by mbacinska** [comment]
yep, ordering of properties and functions could be better

**Comment by dbacinski** [comment]
yep, ordering of properties and functions could be better here

**Comment by dbacinski** [comment]
done https://github.com/dbacinski/Design-Patterns-In-Kotlin/commit/3711a407b3684d5137179af85c7289025167292b
