### ISSUE TITLE
Use a list of observers instead of only one

### ISSUE THREAD

**Issue by uzilan** [dbacinski/Design-Patterns-In-Kotlin#28]
Usually, when implementing the observer pattern, the subject contains a list of observers, so it allows whatever class that is interested in its events to listen to them. In your (however beautiful) example there can be only one observer. So my suggestion is to use a list of observers in the subject, and a method named `addObserver(observer: Any)` to allow adding observers.

**Comment by dbacinski** [comment]
My intention was to choose the simplest possible example of the pattern.

Would it help you to understand the pattern if it would handle multiple listeners? 

To me, it is an additional noise.

**Comment by uzilan** [comment]
I get that, but I think it might over-simplify the pattern, since the idea behind it is that all of the classes that are interested in events can register themselves, which is impossible in that case.

**Comment by dbacinski** [comment]
ok, I have got your point and agree. Would you like to submit a PR?

**Comment by uzilan** [comment]
Will do

**Comment by uzilan** [comment]
Done in https://github.com/dbacinski/Design-Patterns-In-Kotlin/pull/29
