### ISSUE TITLE
request for example of repository pattern, with optional caching

### ISSUE THREAD

**Issue by pabl0rg** [dbacinski/Design-Patterns-In-Kotlin#3]
Hello, 

I have seen some nice repository pattern implementations in Java but cannot find one in Kotlin.

Thanks!

**Comment by dbacinski** [comment]
Can you give a link to Java version? Or post a Gist?

**Comment by pabl0rg** [comment]
Here's the link.  Also written in Poland :)
https://medium.com/@krzychukosobudzki/repository-design-pattern-bc490b256006#.l4uro4rdd

**Comment by dbacinski** [comment]
I can add Repository as a separate pattern but only with dummy implementation like for the other examples. I want to keep it simple.

What you are looking for is a specific implementation of Repository pattern. It is perfectly fine to use the one from link that you have provided and convert it to Kotlin using https://www.jetbrains.com/help/idea/2016.2/converting-a-java-file-to-kotlin-file.html

**Comment by pabl0rg** [comment]
Thanks.  I'm familiar with java -> kotlin conversion (also alt + shift + cmd + k) but i think something more idiomatic could be done that would make it easy to inject a cache and maybe a db provider.

**Comment by pabl0rg** [comment]
Unfortunately, I don't know Japanese but it would be interesting to write in Kotlin something like what they presented here for Swift

https://speakerdeck.com/naoty/repository-pattern-in-swift
