### ISSUE TITLE
Builder and apply

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [dbacinski/Design-Patterns-In-Kotlin#36]
I think that is interesting how you create the builder pattern for learning Kotlin DSL, but why just don't use apply? Maybe add the apply alternative should be great because it is available for all objects out of the box.

**Comment by dbacinski** [comment]
I was thinking about it, but I am not sure if `apply` fulfills Builder definition:
```
The builder pattern is used to create complex objects with constituent parts that must be created in the same order or using a specific algorithm. An external class controls the construction algorithm.
```
To me, it looks like Kotlin DSL is much closer to this definition than `apply`.
