### ISSUE TITLE
How to mock UserRepository?

### ISSUE THREAD

**Issue by SAGARSURI** [dbacinski/Design-Patterns-In-Kotlin#37]
I am planning to write an integration test. But how to mock `UserRepository`. https://github.com/dbacinski/Design-Patterns-In-Kotlin/blob/5b91b34e67fbb5e1938aa0408dd86ec3cc6ba716/patterns/src/test/kotlin/Facade.kt#L41

**Comment by dbacinski** [comment]
You have 2 options:
1. Use mockk  https://mockk.io/ to create a repository which you have control over
2. Introduce interface UserRepository and implement dummy in-memory repository
