### ISSUE TITLE
Wrong usage of an Observer/Listener pattern example

### ISSUE THREAD

**Issue by hawklike** [dbacinski/Design-Patterns-In-Kotlin#40]
I suppose that the usage example of [Observer/Listener](https://github.com/dbacinski/Design-Patterns-In-Kotlin#observer--listener) should be this:
``` kotlin
val textView = TextView().apply {
    listeners.add(PrintingTextChangedListener())
}

with(textView) {
    text = "Lorem ipsum"
    text = "dolor sit amet"
}
```
It is right in the pattern detail though.

**Comment by MirzalievPulat** [comment]
> I suppose that the usage example of [Observer/Listener](https://github.com/dbacinski/Design-Patterns-In-Kotlin#observer--listener) should be this:
> 
> ```kotlin
> val textView = TextView().apply {
>     listeners.add(PrintingTextChangedListener())
> }
> 
> with(textView) {
>     text = "Lorem ipsum"
>     text = "dolor sit amet"
> }
> ```
> 
> It is right in the pattern detail though.

@hawklike you are completely right

**Comment by dbacinski** [comment]
thanks, fixed in https://github.com/dbacinski/Design-Patterns-In-Kotlin/commit/9c86ad0265669da5edd6aca379050cfc2cc2404c
